# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UserLook Blog
email: userlookco@gmail.com
description: >
  Everything about User Testing & Customer Feedback.
logo: "/assets/images/logo.png"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.userlook.co" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Junu'
bio: >
  Hey, Iâ€™m one of the founders of UserLook. Iâ€™m also a design and research nerd on a mission to help others build things people love. Meerkat is my spirit animal and Iâ€™m dreaming of farming humans, animals and robots ğŸ¶ğŸŒ±ğŸ˜Š
author_image: "/assets/images/author.png"
twitter_username: userlookco
github_username:  

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
